# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\rule_show.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChessRule(object):
    def setupUi(self, ChessRule):
        ChessRule.setObjectName("ChessRule")
        ChessRule.resize(450, 500)
        self.gridLayout = QtWidgets.QGridLayout(ChessRule)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(ChessRule)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(ChessRule)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(ChessRule)
        QtCore.QMetaObject.connectSlotsByName(ChessRule)

    def retranslateUi(self, ChessRule):
        _translate = QtCore.QCoreApplication.translate
        ChessRule.setWindowTitle(_translate("ChessRule", "Form"))
        self.pushButton.setText(_translate("ChessRule", "确定"))
